name: deploy_st
channels:
  - conda-forge
dependencies:
  - matplotlib=3.3.4
  - numpy=1.19.2
  - pandas=1.2.3
  - pip=21.0.1
  - python=3.8.12
  - scipy=1.6.1
  - simpy=4.0.1
  - jupyter
  - jupyterlab=3.6.2
  - joblib=1.2.0
  - pip:
    - streamlit
    - treat-sim==0.1.0
